[features]
seeds = false
skip-lint = false

[programs.localnet]
raffle_contract = "9WVXrk3G4XLiKtaqCpViTgNuUodMLaGsqnGqhzPqxrKC"
[programs.devnet]
raffle_contract = "9WVXrk3G4XLiKtaqCpViTgNuUodMLaGsqnGqhzPqxrKC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# cluster = "Localnet"
# wallet = "~/.config/solana/id.json"
wallet = "/Users/mac/Documents/SolanaSmartContracts/KevStudios/raffle-contract/deploywallet/wallet.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
